"""
AUTO-GENERATED canonical unit name set from game_data/unit_db.json.
Used by classify_action() to identify production units vs abilities.
Regenerate by running: python3 build_classifier_data.py
"""

# Set of all known unit names (production-able squads)
UNIT_NAMES = {
    ' 2 1⁄2-ton 6×6 Truck',
    '17-pounder Anti-tank Emplacement',
    '17-pounder Anti-tank Gun Team',
    '18-tonne Recovery Half-track',
    '1⁄4-ton 4x4 Truck',
    '2-pounder Anti-tank Gun Team',
    '2-pounder Light Anti-tank Gun Team',
    '2.5-tonne Cargo Truck',
    '2.5-tonne Fuel Truck',
    '2.5-tonne Medical Truck',
    '2.5-tonne Utility Truck',
    '221 Scout Car',
    '25-pounder Artillery Emplacement',
    '250 Light Carrier',
    '250/3 Funkpanzerwagen',
    '250/9 Armored Half-track',
    '251 Medium Carrier',
    '254 Reconnaissance Tractor',
    '6-pounder Anti-tank Gun Team',
    '8 Rad Armored Car',
    '8 Rad Armored Car (DAK)',
    'AP Shrapnel Minefield',
    'AT Mines G.S.',
    'Air Support Center',
    'Ammunition Storage',
    'Anti-tank Bunker',
    'Anti-tank Gun Team Paradrop',
    'Archer Tank Destroyer',
    'Armory',
    'Artillery Observer Squad',
    'Artillery Officer',
    'Artillery Radio Beacon',
    'Assault Engineer Squad',
    'Assault Engineers',
    'Assault Grenadier Squad',
    'Assault Mechanized Group',
    'Australian Light Infantry Section',
    'B.L. 5.5-Inch Artillery Emplacement',
    'BL5.5 Artillery Emplacement',
    'Barbed Wire Fence',
    'Barracks',
    'Bazooka Squad',
    'Bersaglieri Squad',
    'Bishop Self-propelled Artillery',
    'Bofors Anti-air Emplacement',
    'Bofors Anti-air Gun Team',
    'Booby Trap',
    'Borgward IV Wanze Demolition Vehicle',
    'Butterfly Bomb',
    'CMP 15cwt Truck',
    'Canadian Shock Section',
    'Cannone da 105/28 Howitzer',
    'Captain Retinue',
    'Carro Armato M13/40 Light Tank',
    'Casualty Clearing Bunker',
    'Centaur IV Medium Tank',
    'Centaur Medium Tank',
    'Churchill Black Prince Heavy Tank',
    'Churchill Crocodile Heavy Tank',
    'Churchill IV Heavy Tank',
    'Coastal Reserves Squad',
    'Command Bunker',
    'Command Panzer II Light Tank',
    'Command Panzer IV F Medium Tank',
    'Command Panzer IV Medium Tank',
    'Command Post',
    'Commando Section Paradrop',
    'Commando Support Section Paradrop',
    'Company Command Post',
    'Concrete Bunker',
    'Crusader AA Medium Tank',
    'Crusader II Medium Tank',
    'DM-16 Trip Flare',
    'Dingo Light Scout Car',
    'Elefant Tank Destroyer',
    'Engineer Squad',
    'Fallschirmjäger Squad Paradrop',
    'Fallschirmpioneer Squad Paradrop',
    'Field Hospital',
    'Field Infirmary',
    'Fighting Nest',
    'Fighting Position',
    'Flak 30 Anti-aircraft Gun Team',
    'Flak 36 Anti-tank Emplacement',
    'Flak 36 Anti-tank Gun Team',
    'Flak 38 Anti-air Emplacement',
    'Flak 38 Anti-aircraft Emplacement',
    'Flakvierling Half-track',
    'Flammpanzer III Medium Tank',
    'Foot Guards Section',
    'Forward Repair Assembly',
    'Forward Repair Station',
    'Frontline Medical Station',
    'Goliath Demolition Vehicle',
    'GrW 34 Mortar Team',
    'Grenadier Squad',
    'Guastatori Squad',
    'Gurkha Rifles Section',
    'HMG Bunker',
    'HMG Fighting Position',
    'HMG Nest',
    'Hardpoint',
    'Headquarters',
    'Heavy Machine Gun Paradrop',
    'Heavy Weapon Kompanie',
    'Hidden Demolition Charge',
    'High-Explosive Demolition Charge',
    'High-explosive Demolition Charge',
    'Humber Armored Car',
    'Infanterie Kompanie',
    'Infantry Section',
    'Infantry Station',
    'Infantry Support Center',
    'Intel Radio Beacon',
    'Italian Infantry',
    'Jäger Squad',
    'Kettenkrad Recon Vehicle',
    'King Tiger Heavy Tank',
    'Kradschützen Motorcycle Team',
    'Kriegsmariner Squad',
    'L6/40 Light Flame Tank',
    'L6/40 Light Tank',
    'LG40 Anti-tank Gun Team',
    'LG40 Recoilless Gun Paradrop',
    'Land Mattress Team',
    'Landmine',
    'Light Anti-Tank Mine',
    'Light Support Kompanie',
    'Luftwaffe Kompanie',
    'Luftwaffe Relay Point',
    'M1 Anti-Tank Mine',
    'M1 Anti-tank Gun Team',
    'M1 Mine',
    'M1 Mortar Team',
    'M1 Pack Howitzer Paradrop',
    'M1 Pack Howitzer Team',
    'M16 Multiple Gun Motor Carriage',
    'M18 Hellcat Tank Destroyer',
    'M1919 Machine Gun Team',
    'M24 Chaffee Light Tank',
    'M26 Pershing Heavy Tank',
    'M29 Weasel Recon Vehicle',
    'M2A1 Howitzer Team',
    'M3 75 mm Gun Motor Carriage',
    'M3 Armored Personnel Carrier',
    'M3 Grant Medium Tank',
    'M3 Stuart Light Tank',
    'M31 Recovery Vehicle',
    'M4(105) Sherman Bulldozer',
    'M4A1 Sherman Medium Tank',
    'M4A1 Sherman Whizbang',
    'M4A1(76) Sherman Medium Tank',
    'M4A3E8 Sherman Easy Eight',
    'M4A4 Sherman Firefly Medium Tank',
    'M5 3-inch Anti-tank Gun',
    'M6 Heavy Anti-tank Mine',
    'M8 Greyhound Armored Car',
    'M8 Scott SPG',
    'MG 42 Bunker',
    'MG 42 Machine Gun Team',
    'MG34 Team',
    'ML 3-inch Mortar Team',
    'ML 4.2-inch Heavy Mortar Team',
    'Machine Gun Bunker',
    'Marder III M Tank Destroyer',
    'Marder III Tank Destroyer',
    'Matilda II Heavy Tank',
    'Mechanized Assault Group',
    'Mechanized Kompanie',
    'Mechanized Station',
    'Mechanized Support Center',
    'Medical Bunker',
    'Medical Station',
    'Mobile Command Station',
    'Modified AT Mines G.S.',
    'Mortar Bunker',
    'Mortar Half-track',
    'Mortar Pit',
    'Motor Pool',
    'Nebelwerfer 42 Rocket Launcher Team',
    'Obice da 210/22 Artillery Emplacement',
    'Observation Bunker',
    'Pak 38 Anti-tank Gun Team',
    'Pak 38 Mechanized Group',
    'Pak 40 Anti-tank Gun Team',
    'Panther Heavy Tank',
    'Pantherturm Emplacement',
    'Panzer III Assault Group',
    'Panzer III G Medium Tank',
    'Panzer III L Medium Tank',
    'Panzer III N Medium Tank',
    'Panzer IV Assault Group',
    'Panzer IV Command Tank',
    'Panzer IV F Medium Tank',
    'Panzer IV Medium Tank',
    'Panzer Kompanie',
    'Panzerarmee Kommand',
    'Panzergrenadier Kompanie',
    'Panzergrenadier Squad',
    'Panzergrenadier Squad (DAK)',
    'Panzergrenadier Squad (WEHR)',
    'Panzerjäger Mechanized Group',
    'Panzerjäger Squad',
    'Panzerpioneer Squad',
    'Paradrop Reinforcements',
    'Paratrooper Squad',
    'Paratrooper Squad Paradrop',
    'Pathfinder Squad',
    'Pathfinders',
    'Pioneer Squad',
    'Platoon Command Post',
    'Polish Lancer Section',
    'QF 17-pounder Anti-tank Gun',
    'Radio Beacon',
    'Ranger Squad',
    'Reinforced Barbed Wire',
    'Reinforcement Bunker',
    'Reinforcement Point',
    'Repair Bunker',
    'Resistance Fighter Infiltration',
    'Resource Cache',
    'Riegel 43 Anti-tank Mine',
    'Riflemen Squad',
    'Road Block',
    'Royal Engineer Section',
    'S-Mine Booby Trap',
    'S-minefield',
    'S-minefield Entity',
    'SSF Commando Squad',
    'Saboteur Infiltration',
    'Safe House',
    'Sandbag Wall',
    'Sangar Wall',
    'Schu-mine 42',
    'Scout Squad',
    'Section Command Post',
    'Sector Subterfuge Beacon',
    'Semovente da 75/18 Assault Gun',
    'Sherman VC Firefly Tank Destroyer',
    'Sniper',
    'Sniper (US)',
    'Sniper (WEHR)',
    'Spotter Squad',
    'Stoßtruppen Squad',
    'Strong Point',
    'StuG Assault Group',
    'StuG III D Assault Gun',
    'StuG III G Assault Gun',
    'Sturmpanzer IV Brummbär',
    'Sturmpioneer Squad',
    'Supply Bunker',
    'Tank Depot',
    'Tank Trap',
    'Teller Mine',
    'Tiger Heavy Tank',
    'Timed High-explosive Demo Charge',
    'Towed Cannone da 105/28 Field Howitzer',
    'Towed M5 3-inch Anti-tank Gun',
    'Towed ML 4.2-inch Heavy Mortar',
    'Transfer Depot',
    'Valentine II Medium Tank',
    'Vickers Machine Gun Team',
    'Volunteer Infantry',
    'Walking Stuka Rocket Launcher',
    'Weapon Supply Bunker',
    'Weapon Support Center',
    'Wespe Self-propelled Artillery',
    'Wirbelwind Flakpanzer',
    'le.IG 18 Mechanized Group',
    'le.IG 18 Support Gun Team',
    'leFH 18 Howitzer Emplacement',
}

# Aliases: cohdb name -> game data name
UNIT_ALIASES = {
    '2-pounder Anti-tank Gun Team': '2-pounder Light Anti-tank Gun Team',
    '2.5-tonne Medical Truck': '2.5-tonne Medical Truck',
    'Anti-tank Gun Team Paradrop': 'Anti-tank Gun Team Paradrop',
    'Assault Engineers': 'Assault Engineer Squad',
    'Assault Mechanized Group': 'Assault Mechanized Group',
    'Borgward IV Wanze Demolition Vehicle': 'Borgward IV Wanze',
    'Centaur Medium Tank': 'Centaur IV Medium Tank',
    'Command Panzer IV F Medium Tank': 'Command Panzer IV Medium Tank',
    'Commando Section Paradrop': 'Commando Section Paradrop',
    'Commando Support Section Paradrop': 'Commando Support Section Paradrop',
    'Fallschirmjäger Squad Paradrop': 'Fallschirmjäger Squad',
    'Fallschirmpioneer Squad Paradrop': 'Fallschirmpioneer Squad',
    'Heavy Machine Gun Paradrop': 'Heavy Machine Gun Paradrop',
    'Italian Infantry': 'Italian Infantry',
    'Kriegsmariner Squad': 'Kriegsmariner Squad',
    'LG40 Recoilless Gun Paradrop': 'LG40 Recoilless Gun Paradrop',
    'M1 Pack Howitzer Paradrop': 'M1 Pack Howitzer Paradrop',
    'Mechanized Assault Group': 'Mechanized Assault Group',
    'Pak 38 Mechanized Group': 'Pak 38 Anti-tank Gun Team',
    'Panzer III Assault Group': 'Panzer III Assault Group',
    'Panzer IV Assault Group': 'Panzer IV Assault Group',
    'Panzer IV Command Tank': 'Command Panzer IV Medium Tank',
    'Panzerjäger Mechanized Group': 'Panzerjäger Squad',
    'Paradrop Reinforcements': 'Paradrop Reinforcements',
    'Paratrooper Squad Paradrop': 'Paratrooper Squad',
    'Pathfinders': 'Pathfinders',
    'Resistance Fighter Infiltration': 'Resistance Fighter Squad',
    'Saboteur Infiltration': 'Saboteur Infiltration',
    'StuG Assault Group': 'StuG Assault Group',
    'Sturmpioneer Squad': 'Sturmpioneers',
    'Towed Cannone da 105/28 Field Howitzer': 'Cannone da 105/28 Howitzer',
    'Towed M5 3-inch Anti-tank Gun': 'M5 3-inch Anti-tank Gun',
    'Towed ML 4.2-inch Heavy Mortar': 'ML 4.2-inch Heavy Mortar Team',
    'Volunteer Infantry': 'Volunteer Infantry',
    'le.IG 18 Mechanized Group': 'le.IG 18 Support Gun Team',
}


def is_unit(name: str) -> bool:
    """Check if a name refers to a producible unit."""
    return name in UNIT_NAMES or name in UNIT_ALIASES


def canonicalize(name: str) -> str:
    """Return the canonical game-data name for a cohdb unit name."""
    return UNIT_ALIASES.get(name, name)
