"""
AUTO-GENERATED canonical unit name set from game_data/unit_db.json.
Used by classify_action() to identify production units vs abilities.
Regenerate by running: python3 build_classifier_data.py
"""

# Set of all known unit names (production-able squads)
UNIT_NAMES = {
    ' 2 1⁄2-ton 6×6 Truck',
    '17-pounder Anti-tank Emplacement',
    '17-pounder Anti-tank Gun Team',
    '18-tonne Recovery Half-track',
    '1⁄4-ton 4x4 Truck',
    '2-pounder Anti-tank Gun Team',
    '2-pounder Light Anti-tank Gun Team',
    '2.5-tonne Cargo Truck',
    '2.5-tonne Fuel Truck',
    '2.5-tonne Utility Truck',
    '221 Scout Car',
    '25-pounder Artillery Emplacement',
    '250 Light Carrier',
    '250/3 Funkpanzerwagen',
    '250/9 Armored Half-track',
    '251 Medium Carrier',
    '254 Reconnaissance Tractor',
    '6-pounder Anti-tank Gun Team',
    '8 Rad Armored Car',
    '8 Rad Armored Car (DAK)',
    '8 Rad Armored Car (UK)',
    '8 Rad Armored Car (US)',
    '8 Rad Armored Car (WEHR)',
    'AP Shrapnel Minefield',
    'AT Mines G.S.',
    'Air Support Center',
    'Ammunition Storage',
    'Anti-tank Bunker',
    'Archer Tank Destroyer',
    'Armory',
    'Artillery Observer Squad',
    'Artillery Officer',
    'Artillery Radio Beacon',
    'Assault Engineer Squad',
    'Assault Grenadier Squad',
    'Australian Light Infantry Section',
    'B.L. 5.5-Inch Artillery Emplacement',
    'BL5.5 Artillery Emplacement',
    'Barbed Wire Fence',
    'Barracks',
    'Bazooka Squad',
    'Bersaglieri Squad',
    'Bishop Self-propelled Artillery',
    'Bofors Anti-air Emplacement',
    'Bofors Anti-air Gun Team',
    'Booby Trap',
    'Borgward IV Wanze Demolition Vehicle',
    'Butterfly Bomb',
    'CMP 15cwt Truck',
    'Canadian Shock Section',
    'Cannone da 105/28 Howitzer',
    'Captain Retinue',
    'Carro Armato M13/40 Light Tank',
    'Casualty Clearing Bunker',
    'Centaur IV Medium Tank',
    'Churchill Black Prince Heavy Tank',
    'Churchill Crocodile Heavy Tank',
    'Churchill IV Heavy Tank',
    'Coastal Reserves Squad',
    'Command Bunker',
    'Command Panzer II Light Tank',
    'Command Panzer IV F Medium Tank',
    'Command Panzer IV Medium Tank',
    'Command Post',
    'Company Command Post',
    'Concrete Bunker',
    'Crusader AA Medium Tank',
    'Crusader II Medium Tank',
    'DM-16 Trip Flare',
    'Dingo Light Scout Car',
    'Elefant Tank Destroyer',
    'Engineer Squad',
    'Field Hospital',
    'Field Infirmary',
    'Fighting Nest',
    'Fighting Position',
    'Flak 30 Anti-aircraft Gun Team',
    'Flak 36 Anti-tank Emplacement',
    'Flak 36 Anti-tank Gun Team',
    'Flak 38 Anti-air Emplacement',
    'Flak 38 Anti-aircraft Emplacement',
    'Flakvierling Half-track',
    'Flammpanzer III Medium Tank',
    'Foot Guards Section',
    'Forward Repair Assembly',
    'Forward Repair Station',
    'Frontline Medical Station',
    'Goliath Demolition Vehicle',
    'GrW 34 Mortar Team',
    'Grenadier Squad',
    'Guastatori Squad',
    'Gurkha Rifles Section',
    'HMG Bunker',
    'HMG Fighting Position',
    'HMG Nest',
    'Hardpoint',
    'Headquarters',
    'Heavy Weapon Kompanie',
    'Hidden Demolition Charge',
    'High-Explosive Demolition Charge',
    'High-explosive Demolition Charge',
    'Humber Armored Car',
    'Infanterie Kompanie',
    'Infantry Section',
    'Infantry Station',
    'Infantry Support Center',
    'Intel Radio Beacon',
    'Jäger Squad',
    'Kettenkrad Recon Vehicle',
    'King Tiger Heavy Tank',
    'Kradschützen Motorcycle Team',
    'L6/40 Light Flame Tank',
    'L6/40 Light Tank',
    'LG40 Anti-tank Gun Team',
    'Land Mattress Team',
    'Landmine',
    'Light Anti-Tank Mine',
    'Light Support Kompanie',
    'Luftwaffe Kompanie',
    'Luftwaffe Relay Point',
    'M1 Anti-Tank Mine',
    'M1 Anti-tank Gun Team',
    'M1 Mine',
    'M1 Mortar Team',
    'M1 Pack Howitzer Team',
    'M16 Multiple Gun Motor Carriage',
    'M18 Hellcat Tank Destroyer',
    'M1919 Machine Gun Team',
    'M24 Chaffee Light Tank',
    'M26 Pershing Heavy Tank',
    'M29 Weasel Recon Vehicle',
    'M2A1 Howitzer Team',
    'M3 75 mm Gun Motor Carriage',
    'M3 Armored Personnel Carrier',
    'M3 Grant Medium Tank',
    'M3 Stuart Light Tank',
    'M31 Recovery Vehicle',
    'M4(105) Sherman Bulldozer',
    'M4A1 Sherman Medium Tank',
    'M4A1 Sherman Whizbang',
    'M4A1(76) Sherman Medium Tank',
    'M4A3E8 Sherman Easy Eight',
    'M4A4 Sherman Firefly Medium Tank',
    'M5 3-inch Anti-tank Gun',
    'M6 Heavy Anti-tank Mine',
    'M8 Greyhound Armored Car',
    'M8 Scott SPG',
    'MG 42 Bunker',
    'MG 42 Machine Gun Team',
    'MG34 Team',
    'ML 3-inch Mortar Team',
    'ML 4.2-inch Heavy Mortar Team',
    'Machine Gun Bunker',
    'Marder III M Tank Destroyer',
    'Marder III Tank Destroyer',
    'Matilda II Heavy Tank',
    'Mechanized Kompanie',
    'Mechanized Station',
    'Mechanized Support Center',
    'Medical Bunker',
    'Medical Station',
    'Mobile Command Station',
    'Modified AT Mines G.S.',
    'Mortar Bunker',
    'Mortar Half-track',
    'Mortar Pit',
    'Motor Pool',
    'Nebelwerfer 42 Rocket Launcher Team',
    'Obice da 210/22 Artillery Emplacement',
    'Observation Bunker',
    'Pak 38 Anti-tank Gun Team',
    'Pak 40 Anti-tank Gun Team',
    'Panther Heavy Tank',
    'Pantherturm Emplacement',
    'Panzer III G Medium Tank',
    'Panzer III L Medium Tank',
    'Panzer III N Medium Tank',
    'Panzer IV F Medium Tank',
    'Panzer IV Medium Tank',
    'Panzer Kompanie',
    'Panzerarmee Kommand',
    'Panzergrenadier Kompanie',
    'Panzergrenadier Squad',
    'Panzergrenadier Squad (DAK)',
    'Panzergrenadier Squad (UK)',
    'Panzergrenadier Squad (US)',
    'Panzergrenadier Squad (WEHR)',
    'Panzerjäger Squad',
    'Panzerpioneer Squad',
    'Paratrooper Squad',
    'Pathfinder Squad',
    'Pioneer Squad',
    'Platoon Command Post',
    'Polish Lancer Section',
    'QF 17-pounder Anti-tank Gun',
    'Radio Beacon',
    'Ranger Squad',
    'Reinforced Barbed Wire',
    'Reinforcement Bunker',
    'Reinforcement Point',
    'Repair Bunker',
    'Resource Cache',
    'Riegel 43 Anti-tank Mine',
    'Riflemen Squad',
    'Road Block',
    'Royal Engineer Section',
    'S-Mine Booby Trap',
    'S-minefield',
    'S-minefield Entity',
    'SSF Commando Squad',
    'Safe House',
    'Sandbag Wall',
    'Sangar Wall',
    'Schu-mine 42',
    'Scout Squad',
    'Section Command Post',
    'Sector Subterfuge Beacon',
    'Semovente da 75/18 Assault Gun',
    'Sherman VC Firefly Tank Destroyer',
    'Sniper',
    'Sniper (DAK)',
    'Sniper (UK)',
    'Sniper (US)',
    'Sniper (WEHR)',
    'Spotter Squad',
    'Stoßtruppen Squad',
    'Strong Point',
    'StuG III D Assault Gun',
    'StuG III G Assault Gun',
    'Sturmpanzer IV Brummbär',
    'Sturmpioneer Squad',
    'Supply Bunker',
    'Tank Depot',
    'Tank Trap',
    'Teller Mine',
    'Tiger Heavy Tank',
    'Tiger Heavy Tank (DAK)',
    'Tiger Heavy Tank (UK)',
    'Tiger Heavy Tank (US)',
    'Tiger Heavy Tank (WEHR)',
    'Timed High-explosive Demo Charge',
    'Towed Cannone da 105/28 Field Howitzer',
    'Towed ML 4.2-inch Heavy Mortar',
    'Transfer Depot',
    'Valentine II Medium Tank',
    'Vickers Machine Gun Team',
    'Walking Stuka Rocket Launcher',
    'Weapon Supply Bunker',
    'Weapon Support Center',
    'Wespe Self-propelled Artillery',
    'Wirbelwind Flakpanzer',
    'le.IG 18 Support Gun Team',
    'leFH 18 Howitzer Emplacement',
}

# Aliases: cohdb name -> game data name
UNIT_ALIASES = {
    '2-pounder Anti-tank Gun Team': '2-pounder Light Anti-tank Gun Team',
    'Borgward IV Wanze Demolition Vehicle': 'Borgward IV Wanze',
    'Command Panzer IV F Medium Tank': 'Command Panzer IV Medium Tank',
    'Sturmpioneer Squad': 'Sturmpioneers',
    'Towed Cannone da 105/28 Field Howitzer': 'Cannone da 105/28 Howitzer',
    'Towed ML 4.2-inch Heavy Mortar': 'ML 4.2-inch Heavy Mortar Team',
}


def is_unit(name: str) -> bool:
    """Check if a name refers to a producible unit."""
    return name in UNIT_NAMES or name in UNIT_ALIASES


def canonicalize(name: str) -> str:
    """Return the canonical game-data name for a cohdb unit name."""
    return UNIT_ALIASES.get(name, name)
